### Dodaj nową książkę
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Kod Leonarda da Vinci",
  "authorId": 1,
  "categoryId": 1,
  "availableCopies": 3
}

### Edytuj książkę
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "Inferno - Wydanie poprawione",
  "authorId": 1,
  "categoryId": 1,
  "availableCopies": 5
}

### Usuń książkę
DELETE http://localhost:8080/books/1

### Pobierz wszystkie kategorie
GET http://localhost:8080/categories

### Dodaj nową kategorię
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "History"
}

### Dodaj nową kategorię
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Adventure"
}

### Edytuj kategorię
PUT http://localhost:8080/categories/1
Content-Type: application/json

{
  "name": "Updated Adventure"
}